version: '3.8'
services:

    external_resources:
        build: ./external_resources
        container_name: external_resources
        environment: 
            MONGODB_DATABASE: crypto_data
            MONGODB_USERNAME: admin
            MONGODB_PASSWORD: admin
            MONGODB_PORT: 27017
            MONGODB_HOST: 'localhost'
        depends_on: 
            - mongo
        volumes:
            - ./external_resources:/app/external_resources

    mongo:
        container_name: mongodb
        image: mongo:4
        command: mongod --auth  # отключить вход в оболочку mongo без авторизации
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: crypto_data

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        ports: 
            - 8080:8081
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_MONGODB_SERVER=mongodb  # имя контейнера mongodb
        depends_on: 
            - mongo
